### ISSUE TITLE
Version 6.1.0 doesn't build

### ISSUE THREAD

**Issue by cwilling** [universam1/iSpindel#276]
Using fully updated atom/platformio, all previous versions have compiled OK. Since update to 6.1.0 I have the following error:
```
Compiling .pioenvs/d1_mini/FrameworkArduino/cont_util.c.o
pio/lib/Sender/Sender.cpp: In member function 'bool SenderClass::sendGenericPost(String, String, uint16_t)':
pio/lib/Sender/Sender.cpp:168:42: error: no matching function for call to 'HTTPClient::begin(WiFiClient&, String&, uint16_t&, String&)'
http.begin(_client, server, port, url);
^
pio/lib/Sender/Sender.cpp:168:42: note: candidates are:
In file included from pio/lib/Sender/Sender.h:12:0,
from pio/lib/Sender/Sender.cpp:8:
/home/chris/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:136:10: note: bool HTTPClient::begin(String
)
bool begin(String url);
^
/home/chris/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h:136:10: note:   candidate expects 1 argument, 4 provided
```
followed by more unsuitable candidates.

Any ideas why?

I see a recent commit to update for ArduinoJSON v6 - is that relevant to this problem?

Thanks for any help ...

**Comment by universam1** [comment]
pio lib update

**Comment by cwilling** [comment]
Thanks, running ```pio lib update``` did update some things - I now see (amongst others)  ```Updating ArduinoJson  @ 6.10.1  [Up-to-date]```. Unfortunately I still see the same error - I guess it's not related to ArduinoJson after all.

Is there anything else to update?

**Comment by universam1** [comment]
Do the Full Update 

pio upgrade 
Pio update

**Comment by cwilling** [comment]
Thanks, pio upgrade & update worked. It's all building again now.
